### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by marcinlawnik** [caffeinated/widgets#1]
I'd like to write a readme for this, is that okay with you?
Anything I should watch for?

**Comment by kaidesu** [comment]
Go for it! It's certainly something that needs to be done - I just haven't gotten around to it. It's very similar to my Plugins package here: https://github.com/caffeinated/plugins

Nothing to really look out for. If you have any questions just let me know :+1:

**Comment by marcinlawnik** [comment]
An explanation of what it does in one sentence like "Abstraction layer between Blade/Twig to allow the means to "plug in" data through a consistent interface." from your plugin package would be great ;)

**Comment by marcinlawnik** [comment]
Looking through the code, I have no idea what this does. Do you have some example usage I can work with?

**Comment by marcinlawnik** [comment]
Oh, just noticed caffeinated/plugins#1
