### ISSUE TITLE
Class widgets does not exist

### ISSUE THREAD

**Issue by SergeyMiracle** [caffeinated/widgets#4]
When i do register in Service provider 

```
<?php

namespace SOV\Providers;

use Widget;
use Illuminate\Support\ServiceProvider;

class WidgetServiceProvider extends ServiceProvider
{
    /**
     * Bootstrap the application services.
     *
     * @return void
     */
    public function boot()
    {
        //
    }

    /**
     * Register the application services.
     *
     * @return void
     */
    public function register()
    {
        Widget::register('SOV\\Widgets');
    }
}
```

i keep getting error - Class widgets does not exist

**Comment by SergeyMiracle** [comment]
Till it's not resolved i use 

```
 public function register()
    {
        $this->app->widgets->register('SOV\\Widgets');
        //Widget::register('SOV\\\Widgets');
    }
```

**Comment by sebastienheyd** [comment]
You probably load the providers in the wrong order, you must load Caffeinated\Widgets\WidgetsServiceProvider::class before App\Providers\WidgetServiceProvider::class in config/app.php

**Comment by illuminate3** [comment]
I'm having trouble too. IF I place my widget within App/widget it works. If I move it to App/Widget/MyApp then it breaks. Namespacing is being over ridden somewhere I think ....

**Comment by sebastienheyd** [comment]
Have you declare the right namespace into WidgetServiceProvider.php ?

Try this into WidgetServiceProvider.php :

```
Widget::register('App\\Widget\\MyApp');
```
