### ISSUE TITLE
 Is Compatible with caffeinated/modules?

### ISSUE THREAD

**Issue by geo903** [caffeinated/widgets#8]
Hello!
Using three modules:
caffeinated/themes
caffeinated/modules
caffeinated/widgets

Problem with output templates, the code can not find the template in the folder
\app\Modules\Catalog\Resources\Views\widgets

```
   public function handle()
    {

        return Theme::view('widgets.menu');

    }
```

**Comment by kaidesu** [comment]
Gotta reference the namespace for your module if you wish to load a view from it:

`catalog::widgets.menu`

**Comment by geo903** [comment]
Grazie!
